#Use the new container-based infrastructure
sudo: false
language: sourcepawn

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#Webhooks
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c566d34b63ca82e43bbb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#Set the build environment
env:
  - SOURCEMOD=1.7
  - SOURCEMOD=1.8

#And compile!
before_script:
  - wget "http://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O game_upload/sourcemod-$SOURCEMOD-linux.tar.gz
  - cd game_upload
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - cd addons/sourcemod/scripting/
  - wget https://bitbucket.org/GoD_Tony/updater/raw/53ebb3e27e5a43bc46dc52dc0de76ac2fb48cd9e/include/updater.inc -O include/updater.inc
  - chmod +x spcomp

script:
  - ./compile.sh sourcebans.sp sb_admcfg.sp sourcecomms.sp sbchecker.sp SourceSleuth.sp
